In [39]:
import pandas as pd

file_path = "https://data.wprdc.org/dataset/9c7da6cf-7492-4ffc-865d-10945a37232a/resource/967cad5c-ea8f-4558-9dc9-8d3f7a3b046c/download/crime-rate.csv"

# Try reading the CSV file with a different encoding (e.g., 'ISO-8859-1')
df = pd.read_csv(file_path, encoding='ISO-8859-1')

# Drop rows with missing values
df = df.dropna()

# Display the first 69 rows of the DataFrame
df.head(100)

,neighborhood,number_major_crimes_1973,neighborhood_crime_rate_1973,number_major_crimes_1974,neighborhood_crime_rate_1974,number_major_crimes_1975,neighborhood_crime_rate_1975
0,Westwood,65,0.019,46,0.014,78,0.023
1,31st ward,125,0.017,85,0.012,92,0.013
2,Arlington,243,0.037,177,0.027,184,0.028
3,Allegheny Center,277,0.151,407,0.222,571,0.312
4,Allegheny West,154,0.147,197,0.188,227,0.217
...,...,...,...,...,...,...,...
64,Swisshelm Heights,18,0.009,14,0.007,16,0.008
65,Troy Hill,75,0.019,55,0.014,61,0.016
66,Uptown,323,0.099,382,0.117,409,0.126
67,West End,70,0.049,70,0.049,60,0.040
68,Woods Run- Halls Grove,51,0.020,58,0.023,40,0.016

            neighborhood  average_crime_rate
16       Crafton Heights            0.012333
0              31st ward            0.014000
10      Brighton Heights            0.015333
14        Chartiers City            0.016333
11             Brookline            0.018000
12               Carrick            0.018000
6              Beechview            0.018667
5   Banksville-Greentree            0.022667
3              Allentown            0.023000
18      Duquesne Heights            0.024333
9                Bon Air            0.025000
15             City View            0.026333
4              Arlington            0.030667
8             Bloomfield            0.043000
7            Beltzhoover            0.049333
19            East Hills            0.056000
13    Central North Side            0.103667
2         Allegheny West            0.184000
1       Allegheny Center            0.228333
17              Downtown            0.652667